import React from "react";

const Testimonial = props => {
  return (
    <div className={props.className}>
      <div className="d-block w-100 text-center">
        <img
          className="img-fluid"
          src={require(`../../media/AI-generated/${props.AIphoto}`)}
          alt="testimonial"
          style={{ width: "5em", height: "5em" }}
        />
        <h4 className="mt-3 testimonial-title">
          {"Best Organic Store Ever".toUpperCase()}
        </h4>
        <p className="testimonial-content">{props.content}</p>
        {[...Array(props.stars)].map((value,index) => {
          return <i className={`fas fa-medal testimonial-rating`} key={index}></i>;
        })}
        <p className="testimonial-user">{props.author}</p>
        <em>Generated by Testimonial Generator</em>
      </div>
    </div>
  );
};
export default Testimonial;
